/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.uad.exporter;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.PlanEnrollment;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.PlanEnrollmentLocalService;
import com.clarityvisionsolutions.insurance.benefits.tracker.uad.constants.CIBTUADConstants;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Plan Enrollment UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link PlanEnrollmentUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BasePlanEnrollmentUADExporter
	extends DynamicQueryUADExporter<PlanEnrollment> {

	@Override
	public Class<PlanEnrollment> getTypeClass() {
		return PlanEnrollment.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return planEnrollmentLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return CIBTUADConstants.USER_ID_FIELD_NAMES_PLAN_ENROLLMENT;
	}

	@Override
	protected String toXmlString(PlanEnrollment planEnrollment) {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append(
			"com.clarityvisionsolutions.insurance.benefits.tracker.model.PlanEnrollment");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(planEnrollment.getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>memberUserName</column-name><column-value><![CDATA[");
		sb.append(planEnrollment.getMemberUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(planEnrollment.getUserName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected PlanEnrollmentLocalService planEnrollmentLocalService;

}