/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.uad.anonymizer;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.BenefitUsage;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.BenefitUsageLocalService;
import com.clarityvisionsolutions.insurance.benefits.tracker.uad.constants.CIBTUADConstants;

import com.liferay.asset.kernel.model.AssetEntry;
import com.liferay.asset.kernel.service.AssetEntryLocalService;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Benefit Usage UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link BenefitUsageUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseBenefitUsageUADAnonymizer
	extends DynamicQueryUADAnonymizer<BenefitUsage> {

	@Override
	public void autoAnonymize(
			BenefitUsage benefitUsage, long userId, User anonymousUser)
		throws PortalException {

		if (benefitUsage.getUserId() == userId) {
			benefitUsage.setUserId(anonymousUser.getUserId());
			benefitUsage.setUserName(anonymousUser.getFullName());

			autoAnonymizeAssetEntry(benefitUsage, anonymousUser);
		}

		if (benefitUsage.getStatusByUserId() == userId) {
			benefitUsage.setStatusByUserId(anonymousUser.getUserId());
			benefitUsage.setStatusByUserName(anonymousUser.getFullName());
		}

		benefitUsageLocalService.updateBenefitUsage(benefitUsage);
	}

	@Override
	public void delete(BenefitUsage benefitUsage) throws PortalException {
		benefitUsageLocalService.deleteBenefitUsage(benefitUsage);
	}

	@Override
	public Class<BenefitUsage> getTypeClass() {
		return BenefitUsage.class;
	}

	protected void autoAnonymizeAssetEntry(
		BenefitUsage benefitUsage, User anonymousUser) {

		AssetEntry assetEntry = fetchAssetEntry(benefitUsage);

		if (assetEntry != null) {
			assetEntry.setUserId(anonymousUser.getUserId());
			assetEntry.setUserName(anonymousUser.getFullName());

			assetEntryLocalService.updateAssetEntry(assetEntry);
		}
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return benefitUsageLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return CIBTUADConstants.USER_ID_FIELD_NAMES_BENEFIT_USAGE;
	}

	protected AssetEntry fetchAssetEntry(BenefitUsage benefitUsage) {
		return assetEntryLocalService.fetchEntry(
			BenefitUsage.class.getName(), benefitUsage.getBenefitUsageId());
	}

	@Reference
	protected AssetEntryLocalService assetEntryLocalService;

	@Reference
	protected BenefitUsageLocalService benefitUsageLocalService;

}