/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.uad.anonymizer;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.InsurancePlan;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.InsurancePlanLocalService;
import com.clarityvisionsolutions.insurance.benefits.tracker.uad.constants.CIBTUADConstants;

import com.liferay.asset.kernel.model.AssetEntry;
import com.liferay.asset.kernel.service.AssetEntryLocalService;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Insurance Plan UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link InsurancePlanUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseInsurancePlanUADAnonymizer
	extends DynamicQueryUADAnonymizer<InsurancePlan> {

	@Override
	public void autoAnonymize(
			InsurancePlan insurancePlan, long userId, User anonymousUser)
		throws PortalException {

		if (insurancePlan.getUserId() == userId) {
			insurancePlan.setUserId(anonymousUser.getUserId());
			insurancePlan.setUserName(anonymousUser.getFullName());

			autoAnonymizeAssetEntry(insurancePlan, anonymousUser);
		}

		if (insurancePlan.getStatusByUserId() == userId) {
			insurancePlan.setStatusByUserId(anonymousUser.getUserId());
			insurancePlan.setStatusByUserName(anonymousUser.getFullName());
		}

		insurancePlanLocalService.updateInsurancePlan(insurancePlan);
	}

	@Override
	public void delete(InsurancePlan insurancePlan) throws PortalException {
		insurancePlanLocalService.deleteInsurancePlan(insurancePlan);
	}

	@Override
	public Class<InsurancePlan> getTypeClass() {
		return InsurancePlan.class;
	}

	protected void autoAnonymizeAssetEntry(
		InsurancePlan insurancePlan, User anonymousUser) {

		AssetEntry assetEntry = fetchAssetEntry(insurancePlan);

		if (assetEntry != null) {
			assetEntry.setUserId(anonymousUser.getUserId());
			assetEntry.setUserName(anonymousUser.getFullName());

			assetEntryLocalService.updateAssetEntry(assetEntry);
		}
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return insurancePlanLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return CIBTUADConstants.USER_ID_FIELD_NAMES_INSURANCE_PLAN;
	}

	protected AssetEntry fetchAssetEntry(InsurancePlan insurancePlan) {
		return assetEntryLocalService.fetchEntry(
			InsurancePlan.class.getName(), insurancePlan.getInsurancePlanId());
	}

	@Reference
	protected AssetEntryLocalService assetEntryLocalService;

	@Reference
	protected InsurancePlanLocalService insurancePlanLocalService;

}