/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.uad.anonymizer;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.PlanEnrollment;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.PlanEnrollmentLocalService;
import com.clarityvisionsolutions.insurance.benefits.tracker.uad.constants.CIBTUADConstants;

import com.liferay.asset.kernel.model.AssetEntry;
import com.liferay.asset.kernel.service.AssetEntryLocalService;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Plan Enrollment UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link PlanEnrollmentUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BasePlanEnrollmentUADAnonymizer
	extends DynamicQueryUADAnonymizer<PlanEnrollment> {

	@Override
	public void autoAnonymize(
			PlanEnrollment planEnrollment, long userId, User anonymousUser)
		throws PortalException {

		if (planEnrollment.getUserId() == userId) {
			planEnrollment.setUserId(anonymousUser.getUserId());
			planEnrollment.setUserName(anonymousUser.getFullName());

			autoAnonymizeAssetEntry(planEnrollment, anonymousUser);
		}

		if (planEnrollment.getMemberUserId() == userId) {
			planEnrollment.setMemberUserId(anonymousUser.getUserId());
			planEnrollment.setMemberUserName(anonymousUser.getFullName());
		}

		if (planEnrollment.getStatusByUserId() == userId) {
			planEnrollment.setStatusByUserId(anonymousUser.getUserId());
			planEnrollment.setStatusByUserName(anonymousUser.getFullName());
		}

		planEnrollmentLocalService.updatePlanEnrollment(planEnrollment);
	}

	@Override
	public void delete(PlanEnrollment planEnrollment) throws PortalException {
		planEnrollmentLocalService.deletePlanEnrollment(planEnrollment);
	}

	@Override
	public Class<PlanEnrollment> getTypeClass() {
		return PlanEnrollment.class;
	}

	protected void autoAnonymizeAssetEntry(
		PlanEnrollment planEnrollment, User anonymousUser) {

		AssetEntry assetEntry = fetchAssetEntry(planEnrollment);

		if (assetEntry != null) {
			assetEntry.setUserId(anonymousUser.getUserId());
			assetEntry.setUserName(anonymousUser.getFullName());

			assetEntryLocalService.updateAssetEntry(assetEntry);
		}
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return planEnrollmentLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return CIBTUADConstants.USER_ID_FIELD_NAMES_PLAN_ENROLLMENT;
	}

	protected AssetEntry fetchAssetEntry(PlanEnrollment planEnrollment) {
		return assetEntryLocalService.fetchEntry(
			PlanEnrollment.class.getName(),
			planEnrollment.getPlanEnrollmentId());
	}

	@Reference
	protected AssetEntryLocalService assetEntryLocalService;

	@Reference
	protected PlanEnrollmentLocalService planEnrollmentLocalService;

}