/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InsurancePlan service. Represents a row in the &quot;CIBT_InsurancePlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.InsurancePlanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.InsurancePlanImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InsurancePlan
 * @generated
 */
@ProviderType
public interface InsurancePlanModel
	extends BaseModel<InsurancePlan>, ContainerModel, CTModel<InsurancePlan>,
			ExternalReferenceCodeModel, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel, TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Insurance Plan model instance should use the {@link InsurancePlan} interface instead.
	 */

	/**
	 * Returns the primary key of this Insurance Plan.
	 *
	 * @return the primary key of this Insurance Plan
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Insurance Plan.
	 *
	 * @param primaryKey the primary key of this Insurance Plan
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this Insurance Plan.
	 *
	 * @return the mvcc version of this Insurance Plan
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this Insurance Plan.
	 *
	 * @param mvccVersion the mvcc version of this Insurance Plan
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this Insurance Plan.
	 *
	 * @return the ct collection ID of this Insurance Plan
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this Insurance Plan.
	 *
	 * @param ctCollectionId the ct collection ID of this Insurance Plan
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the uuid of this Insurance Plan.
	 *
	 * @return the uuid of this Insurance Plan
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this Insurance Plan.
	 *
	 * @param uuid the uuid of this Insurance Plan
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this Insurance Plan.
	 *
	 * @return the external reference code of this Insurance Plan
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this Insurance Plan.
	 *
	 * @param externalReferenceCode the external reference code of this Insurance Plan
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the insurance plan ID of this Insurance Plan.
	 *
	 * @return the insurance plan ID of this Insurance Plan
	 */
	public long getInsurancePlanId();

	/**
	 * Sets the insurance plan ID of this Insurance Plan.
	 *
	 * @param insurancePlanId the insurance plan ID of this Insurance Plan
	 */
	public void setInsurancePlanId(long insurancePlanId);

	/**
	 * Returns the group ID of this Insurance Plan.
	 *
	 * @return the group ID of this Insurance Plan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this Insurance Plan.
	 *
	 * @param groupId the group ID of this Insurance Plan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this Insurance Plan.
	 *
	 * @return the company ID of this Insurance Plan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this Insurance Plan.
	 *
	 * @param companyId the company ID of this Insurance Plan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this Insurance Plan.
	 *
	 * @return the user ID of this Insurance Plan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this Insurance Plan.
	 *
	 * @param userId the user ID of this Insurance Plan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Insurance Plan.
	 *
	 * @return the user uuid of this Insurance Plan
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this Insurance Plan.
	 *
	 * @param userUuid the user uuid of this Insurance Plan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this Insurance Plan.
	 *
	 * @return the user name of this Insurance Plan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this Insurance Plan.
	 *
	 * @param userName the user name of this Insurance Plan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this Insurance Plan.
	 *
	 * @return the create date of this Insurance Plan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this Insurance Plan.
	 *
	 * @param createDate the create date of this Insurance Plan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Insurance Plan.
	 *
	 * @return the modified date of this Insurance Plan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Insurance Plan.
	 *
	 * @param modifiedDate the modified date of this Insurance Plan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the plan name of this Insurance Plan.
	 *
	 * @return the plan name of this Insurance Plan
	 */
	@AutoEscape
	public String getPlanName();

	/**
	 * Sets the plan name of this Insurance Plan.
	 *
	 * @param planName the plan name of this Insurance Plan
	 */
	public void setPlanName(String planName);

	/**
	 * Returns the provider name of this Insurance Plan.
	 *
	 * @return the provider name of this Insurance Plan
	 */
	@AutoEscape
	public String getProviderName();

	/**
	 * Sets the provider name of this Insurance Plan.
	 *
	 * @param providerName the provider name of this Insurance Plan
	 */
	public void setProviderName(String providerName);

	/**
	 * Returns the active of this Insurance Plan.
	 *
	 * @return the active of this Insurance Plan
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this Insurance Plan is active.
	 *
	 * @return <code>true</code> if this Insurance Plan is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this Insurance Plan is active.
	 *
	 * @param active the active of this Insurance Plan
	 */
	public void setActive(boolean active);

	/**
	 * Returns the annual exam allowance cents of this Insurance Plan.
	 *
	 * @return the annual exam allowance cents of this Insurance Plan
	 */
	public long getAnnualExamAllowanceCents();

	/**
	 * Sets the annual exam allowance cents of this Insurance Plan.
	 *
	 * @param annualExamAllowanceCents the annual exam allowance cents of this Insurance Plan
	 */
	public void setAnnualExamAllowanceCents(long annualExamAllowanceCents);

	/**
	 * Returns the annual frames allowance cents of this Insurance Plan.
	 *
	 * @return the annual frames allowance cents of this Insurance Plan
	 */
	public long getAnnualFramesAllowanceCents();

	/**
	 * Sets the annual frames allowance cents of this Insurance Plan.
	 *
	 * @param annualFramesAllowanceCents the annual frames allowance cents of this Insurance Plan
	 */
	public void setAnnualFramesAllowanceCents(long annualFramesAllowanceCents);

	/**
	 * Returns the annual lenses allowance cents of this Insurance Plan.
	 *
	 * @return the annual lenses allowance cents of this Insurance Plan
	 */
	public long getAnnualLensesAllowanceCents();

	/**
	 * Sets the annual lenses allowance cents of this Insurance Plan.
	 *
	 * @param annualLensesAllowanceCents the annual lenses allowance cents of this Insurance Plan
	 */
	public void setAnnualLensesAllowanceCents(long annualLensesAllowanceCents);

	/**
	 * Returns the annual contacts allowance cents of this Insurance Plan.
	 *
	 * @return the annual contacts allowance cents of this Insurance Plan
	 */
	public long getAnnualContactsAllowanceCents();

	/**
	 * Sets the annual contacts allowance cents of this Insurance Plan.
	 *
	 * @param annualContactsAllowanceCents the annual contacts allowance cents of this Insurance Plan
	 */
	public void setAnnualContactsAllowanceCents(
		long annualContactsAllowanceCents);

	/**
	 * Returns the coverage period months of this Insurance Plan.
	 *
	 * @return the coverage period months of this Insurance Plan
	 */
	public int getCoveragePeriodMonths();

	/**
	 * Sets the coverage period months of this Insurance Plan.
	 *
	 * @param coveragePeriodMonths the coverage period months of this Insurance Plan
	 */
	public void setCoveragePeriodMonths(int coveragePeriodMonths);

	/**
	 * Returns the status of this Insurance Plan.
	 *
	 * @return the status of this Insurance Plan
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this Insurance Plan.
	 *
	 * @param status the status of this Insurance Plan
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this Insurance Plan.
	 *
	 * @return the status by user ID of this Insurance Plan
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this Insurance Plan.
	 *
	 * @param statusByUserId the status by user ID of this Insurance Plan
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this Insurance Plan.
	 *
	 * @return the status by user uuid of this Insurance Plan
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this Insurance Plan.
	 *
	 * @param statusByUserUuid the status by user uuid of this Insurance Plan
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this Insurance Plan.
	 *
	 * @return the status by user name of this Insurance Plan
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this Insurance Plan.
	 *
	 * @param statusByUserName the status by user name of this Insurance Plan
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this Insurance Plan.
	 *
	 * @return the status date of this Insurance Plan
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this Insurance Plan.
	 *
	 * @param statusDate the status date of this Insurance Plan
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the class primary key of the trash entry for this Insurance Plan.
	 *
	 * @return the class primary key of the trash entry for this Insurance Plan
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns <code>true</code> if this Insurance Plan is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this Insurance Plan is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if this Insurance Plan is approved.
	 *
	 * @return <code>true</code> if this Insurance Plan is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this Insurance Plan is denied.
	 *
	 * @return <code>true</code> if this Insurance Plan is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this Insurance Plan is a draft.
	 *
	 * @return <code>true</code> if this Insurance Plan is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this Insurance Plan is expired.
	 *
	 * @return <code>true</code> if this Insurance Plan is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this Insurance Plan is inactive.
	 *
	 * @return <code>true</code> if this Insurance Plan is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this Insurance Plan is incomplete.
	 *
	 * @return <code>true</code> if this Insurance Plan is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this Insurance Plan is pending.
	 *
	 * @return <code>true</code> if this Insurance Plan is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this Insurance Plan is scheduled.
	 *
	 * @return <code>true</code> if this Insurance Plan is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	/**
	 * Returns the container model ID of this Insurance Plan.
	 *
	 * @return the container model ID of this Insurance Plan
	 */
	@Override
	public long getContainerModelId();

	/**
	 * Sets the container model ID of this Insurance Plan.
	 *
	 * @param containerModelId the container model ID of this Insurance Plan
	 */
	@Override
	public void setContainerModelId(long containerModelId);

	/**
	 * Returns the container name of this Insurance Plan.
	 *
	 * @return the container name of this Insurance Plan
	 */
	@Override
	public String getContainerModelName();

	/**
	 * Returns the parent container model ID of this Insurance Plan.
	 *
	 * @return the parent container model ID of this Insurance Plan
	 */
	@Override
	public long getParentContainerModelId();

	/**
	 * Sets the parent container model ID of this Insurance Plan.
	 *
	 * @param parentContainerModelId the parent container model ID of this Insurance Plan
	 */
	@Override
	public void setParentContainerModelId(long parentContainerModelId);

	@Override
	public InsurancePlan cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}