/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.service.base;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.BenefitUsage;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.BenefitUsageLocalService;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.BenefitUsagePersistence;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.InsurancePlanPersistence;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.PlanEnrollmentPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandler;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerRegistryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Criterion;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Disjunction;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Property;
import com.liferay.portal.kernel.dao.orm.PropertyFactoryUtil;
import com.liferay.portal.kernel.dao.orm.RestrictionsFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Benefit Usage local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.clarityvisionsolutions.insurance.benefits.tracker.service.impl.BenefitUsageLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.clarityvisionsolutions.insurance.benefits.tracker.service.impl.BenefitUsageLocalServiceImpl
 * @generated
 */
public abstract class BenefitUsageLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, BenefitUsageLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>BenefitUsageLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.clarityvisionsolutions.insurance.benefits.tracker.service.BenefitUsageLocalServiceUtil</code>.
	 */

	/**
	 * Adds the Benefit Usage to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BenefitUsageLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param benefitUsage the Benefit Usage
	 * @return the Benefit Usage that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BenefitUsage addBenefitUsage(BenefitUsage benefitUsage) {
		benefitUsage.setNew(true);

		return benefitUsagePersistence.update(benefitUsage);
	}

	/**
	 * Creates a new Benefit Usage with the primary key. Does not add the Benefit Usage to the database.
	 *
	 * @param benefitUsageId the primary key for the new Benefit Usage
	 * @return the new Benefit Usage
	 */
	@Override
	@Transactional(enabled = false)
	public BenefitUsage createBenefitUsage(long benefitUsageId) {
		return benefitUsagePersistence.create(benefitUsageId);
	}

	/**
	 * Deletes the Benefit Usage with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BenefitUsageLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param benefitUsageId the primary key of the Benefit Usage
	 * @return the Benefit Usage that was removed
	 * @throws PortalException if a Benefit Usage with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BenefitUsage deleteBenefitUsage(long benefitUsageId)
		throws PortalException {

		return benefitUsagePersistence.remove(benefitUsageId);
	}

	/**
	 * Deletes the Benefit Usage from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BenefitUsageLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param benefitUsage the Benefit Usage
	 * @return the Benefit Usage that was removed
	 * @throws PortalException
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BenefitUsage deleteBenefitUsage(BenefitUsage benefitUsage)
		throws PortalException {

		return benefitUsagePersistence.remove(benefitUsage);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return benefitUsagePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			BenefitUsage.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return benefitUsagePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.BenefitUsageModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return benefitUsagePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.BenefitUsageModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return benefitUsagePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return benefitUsagePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return benefitUsagePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public BenefitUsage fetchBenefitUsage(long benefitUsageId) {
		return benefitUsagePersistence.fetchByPrimaryKey(benefitUsageId);
	}

	/**
	 * Returns the Benefit Usage matching the UUID and group.
	 *
	 * @param uuid the Benefit Usage's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Benefit Usage, or <code>null</code> if a matching Benefit Usage could not be found
	 */
	@Override
	public BenefitUsage fetchBenefitUsageByUuidAndGroupId(
		String uuid, long groupId) {

		return benefitUsagePersistence.fetchByUUID_G(uuid, groupId);
	}

	@Override
	public BenefitUsage fetchBenefitUsageByExternalReferenceCode(
		String externalReferenceCode, long groupId) {

		return benefitUsagePersistence.fetchByERC_G(
			externalReferenceCode, groupId);
	}

	@Override
	public BenefitUsage getBenefitUsageByExternalReferenceCode(
			String externalReferenceCode, long groupId)
		throws PortalException {

		return benefitUsagePersistence.findByERC_G(
			externalReferenceCode, groupId);
	}

	/**
	 * Returns the Benefit Usage with the primary key.
	 *
	 * @param benefitUsageId the primary key of the Benefit Usage
	 * @return the Benefit Usage
	 * @throws PortalException if a Benefit Usage with the primary key could not be found
	 */
	@Override
	public BenefitUsage getBenefitUsage(long benefitUsageId)
		throws PortalException {

		return benefitUsagePersistence.findByPrimaryKey(benefitUsageId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(benefitUsageLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BenefitUsage.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("benefitUsageId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			benefitUsageLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(BenefitUsage.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"benefitUsageId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(benefitUsageLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BenefitUsage.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("benefitUsageId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					Criterion modifiedDateCriterion =
						portletDataContext.getDateRangeCriteria("modifiedDate");

					Criterion statusDateCriterion =
						portletDataContext.getDateRangeCriteria("statusDate");

					if ((modifiedDateCriterion != null) &&
						(statusDateCriterion != null)) {

						Disjunction disjunction =
							RestrictionsFactoryUtil.disjunction();

						disjunction.add(modifiedDateCriterion);
						disjunction.add(statusDateCriterion);

						dynamicQuery.add(disjunction);
					}

					Property workflowStatusProperty =
						PropertyFactoryUtil.forName("status");

					if (portletDataContext.isInitialPublication()) {
						dynamicQuery.add(
							workflowStatusProperty.ne(
								WorkflowConstants.STATUS_IN_TRASH));
					}
					else {
						StagedModelDataHandler<?> stagedModelDataHandler =
							StagedModelDataHandlerRegistryUtil.
								getStagedModelDataHandler(
									BenefitUsage.class.getName());

						dynamicQuery.add(
							workflowStatusProperty.in(
								stagedModelDataHandler.
									getExportableStatuses()));
					}
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<BenefitUsage>() {

				@Override
				public void performAction(BenefitUsage benefitUsage)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, benefitUsage);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(BenefitUsage.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return benefitUsagePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement BenefitUsageLocalServiceImpl#deleteBenefitUsage(BenefitUsage) to avoid orphaned data");
		}

		return benefitUsageLocalService.deleteBenefitUsage(
			(BenefitUsage)persistedModel);
	}

	@Override
	public BasePersistence<BenefitUsage> getBasePersistence() {
		return benefitUsagePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return benefitUsagePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the Benefit Usages matching the UUID and company.
	 *
	 * @param uuid the UUID of the Benefit Usages
	 * @param companyId the primary key of the company
	 * @return the matching Benefit Usages, or an empty list if no matches were found
	 */
	@Override
	public List<BenefitUsage> getBenefitUsagesByUuidAndCompanyId(
		String uuid, long companyId) {

		return benefitUsagePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of Benefit Usages matching the UUID and company.
	 *
	 * @param uuid the UUID of the Benefit Usages
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of Benefit Usages
	 * @param end the upper bound of the range of Benefit Usages (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching Benefit Usages, or an empty list if no matches were found
	 */
	@Override
	public List<BenefitUsage> getBenefitUsagesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<BenefitUsage> orderByComparator) {

		return benefitUsagePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the Benefit Usage matching the UUID and group.
	 *
	 * @param uuid the Benefit Usage's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Benefit Usage
	 * @throws PortalException if a matching Benefit Usage could not be found
	 */
	@Override
	public BenefitUsage getBenefitUsageByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return benefitUsagePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the Benefit Usages.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.BenefitUsageModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of Benefit Usages
	 * @param end the upper bound of the range of Benefit Usages (not inclusive)
	 * @return the range of Benefit Usages
	 */
	@Override
	public List<BenefitUsage> getBenefitUsages(int start, int end) {
		return benefitUsagePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of Benefit Usages.
	 *
	 * @return the number of Benefit Usages
	 */
	@Override
	public int getBenefitUsagesCount() {
		return benefitUsagePersistence.countAll();
	}

	/**
	 * Updates the Benefit Usage in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BenefitUsageLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param benefitUsage the Benefit Usage
	 * @return the Benefit Usage that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BenefitUsage updateBenefitUsage(BenefitUsage benefitUsage) {
		return benefitUsagePersistence.update(benefitUsage);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			BenefitUsageLocalService.class, IdentifiableOSGiService.class,
			CTService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		benefitUsageLocalService = (BenefitUsageLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BenefitUsageLocalService.class.getName();
	}

	@Override
	public CTPersistence<BenefitUsage> getCTPersistence() {
		return benefitUsagePersistence;
	}

	@Override
	public Class<BenefitUsage> getModelClass() {
		return BenefitUsage.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<BenefitUsage>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(benefitUsagePersistence);
	}

	protected String getModelClassName() {
		return BenefitUsage.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = benefitUsagePersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected BenefitUsageLocalService benefitUsageLocalService;

	@Reference
	protected BenefitUsagePersistence benefitUsagePersistence;

	@Reference
	protected InsurancePlanPersistence insurancePlanPersistence;

	@Reference
	protected PlanEnrollmentPersistence planEnrollmentPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		BenefitUsageLocalServiceBaseImpl.class);

}