/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.service.base;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.InsurancePlan;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.InsurancePlanService;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.BenefitUsagePersistence;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.InsurancePlanPersistence;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.PlanEnrollmentPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import java.sql.Connection;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Insurance Plan remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.clarityvisionsolutions.insurance.benefits.tracker.service.impl.InsurancePlanServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.clarityvisionsolutions.insurance.benefits.tracker.service.impl.InsurancePlanServiceImpl
 * @generated
 */
public abstract class InsurancePlanServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, InsurancePlanService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>InsurancePlanService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.clarityvisionsolutions.insurance.benefits.tracker.service.InsurancePlanServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			InsurancePlanService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		insurancePlanService = (InsurancePlanService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return InsurancePlanService.class.getName();
	}

	protected Class<?> getModelClass() {
		return InsurancePlan.class;
	}

	protected String getModelClassName() {
		return InsurancePlan.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = insurancePlanPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected BenefitUsagePersistence benefitUsagePersistence;

	@Reference
	protected com.clarityvisionsolutions.insurance.benefits.tracker.service.
		InsurancePlanLocalService insurancePlanLocalService;

	protected InsurancePlanService insurancePlanService;

	@Reference
	protected InsurancePlanPersistence insurancePlanPersistence;

	@Reference
	protected PlanEnrollmentPersistence planEnrollmentPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		InsurancePlanServiceBaseImpl.class);

}