/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.service.base;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.InsurancePlan;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.InsurancePlanLocalService;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.BenefitUsagePersistence;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.InsurancePlanPersistence;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.PlanEnrollmentPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandler;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerRegistryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Criterion;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Disjunction;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Property;
import com.liferay.portal.kernel.dao.orm.PropertyFactoryUtil;
import com.liferay.portal.kernel.dao.orm.RestrictionsFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Insurance Plan local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.clarityvisionsolutions.insurance.benefits.tracker.service.impl.InsurancePlanLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.clarityvisionsolutions.insurance.benefits.tracker.service.impl.InsurancePlanLocalServiceImpl
 * @generated
 */
public abstract class InsurancePlanLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, InsurancePlanLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>InsurancePlanLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.clarityvisionsolutions.insurance.benefits.tracker.service.InsurancePlanLocalServiceUtil</code>.
	 */

	/**
	 * Adds the Insurance Plan to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InsurancePlanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param insurancePlan the Insurance Plan
	 * @return the Insurance Plan that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public InsurancePlan addInsurancePlan(InsurancePlan insurancePlan) {
		insurancePlan.setNew(true);

		return insurancePlanPersistence.update(insurancePlan);
	}

	/**
	 * Creates a new Insurance Plan with the primary key. Does not add the Insurance Plan to the database.
	 *
	 * @param insurancePlanId the primary key for the new Insurance Plan
	 * @return the new Insurance Plan
	 */
	@Override
	@Transactional(enabled = false)
	public InsurancePlan createInsurancePlan(long insurancePlanId) {
		return insurancePlanPersistence.create(insurancePlanId);
	}

	/**
	 * Deletes the Insurance Plan with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InsurancePlanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param insurancePlanId the primary key of the Insurance Plan
	 * @return the Insurance Plan that was removed
	 * @throws PortalException if a Insurance Plan with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public InsurancePlan deleteInsurancePlan(long insurancePlanId)
		throws PortalException {

		return insurancePlanPersistence.remove(insurancePlanId);
	}

	/**
	 * Deletes the Insurance Plan from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InsurancePlanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param insurancePlan the Insurance Plan
	 * @return the Insurance Plan that was removed
	 * @throws PortalException
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public InsurancePlan deleteInsurancePlan(InsurancePlan insurancePlan)
		throws PortalException {

		return insurancePlanPersistence.remove(insurancePlan);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return insurancePlanPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			InsurancePlan.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return insurancePlanPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.InsurancePlanModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return insurancePlanPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.InsurancePlanModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return insurancePlanPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return insurancePlanPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return insurancePlanPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public InsurancePlan fetchInsurancePlan(long insurancePlanId) {
		return insurancePlanPersistence.fetchByPrimaryKey(insurancePlanId);
	}

	/**
	 * Returns the Insurance Plan matching the UUID and group.
	 *
	 * @param uuid the Insurance Plan's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Insurance Plan, or <code>null</code> if a matching Insurance Plan could not be found
	 */
	@Override
	public InsurancePlan fetchInsurancePlanByUuidAndGroupId(
		String uuid, long groupId) {

		return insurancePlanPersistence.fetchByUUID_G(uuid, groupId);
	}

	@Override
	public InsurancePlan fetchInsurancePlanByExternalReferenceCode(
		String externalReferenceCode, long groupId) {

		return insurancePlanPersistence.fetchByERC_G(
			externalReferenceCode, groupId);
	}

	@Override
	public InsurancePlan getInsurancePlanByExternalReferenceCode(
			String externalReferenceCode, long groupId)
		throws PortalException {

		return insurancePlanPersistence.findByERC_G(
			externalReferenceCode, groupId);
	}

	/**
	 * Returns the Insurance Plan with the primary key.
	 *
	 * @param insurancePlanId the primary key of the Insurance Plan
	 * @return the Insurance Plan
	 * @throws PortalException if a Insurance Plan with the primary key could not be found
	 */
	@Override
	public InsurancePlan getInsurancePlan(long insurancePlanId)
		throws PortalException {

		return insurancePlanPersistence.findByPrimaryKey(insurancePlanId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(insurancePlanLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(InsurancePlan.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("insurancePlanId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			insurancePlanLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(InsurancePlan.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"insurancePlanId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(insurancePlanLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(InsurancePlan.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("insurancePlanId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					Criterion modifiedDateCriterion =
						portletDataContext.getDateRangeCriteria("modifiedDate");

					Criterion statusDateCriterion =
						portletDataContext.getDateRangeCriteria("statusDate");

					if ((modifiedDateCriterion != null) &&
						(statusDateCriterion != null)) {

						Disjunction disjunction =
							RestrictionsFactoryUtil.disjunction();

						disjunction.add(modifiedDateCriterion);
						disjunction.add(statusDateCriterion);

						dynamicQuery.add(disjunction);
					}

					Property workflowStatusProperty =
						PropertyFactoryUtil.forName("status");

					if (portletDataContext.isInitialPublication()) {
						dynamicQuery.add(
							workflowStatusProperty.ne(
								WorkflowConstants.STATUS_IN_TRASH));
					}
					else {
						StagedModelDataHandler<?> stagedModelDataHandler =
							StagedModelDataHandlerRegistryUtil.
								getStagedModelDataHandler(
									InsurancePlan.class.getName());

						dynamicQuery.add(
							workflowStatusProperty.in(
								stagedModelDataHandler.
									getExportableStatuses()));
					}
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<InsurancePlan>() {

				@Override
				public void performAction(InsurancePlan insurancePlan)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, insurancePlan);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(InsurancePlan.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return insurancePlanPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement InsurancePlanLocalServiceImpl#deleteInsurancePlan(InsurancePlan) to avoid orphaned data");
		}

		return insurancePlanLocalService.deleteInsurancePlan(
			(InsurancePlan)persistedModel);
	}

	@Override
	public BasePersistence<InsurancePlan> getBasePersistence() {
		return insurancePlanPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return insurancePlanPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the Insurance Plans matching the UUID and company.
	 *
	 * @param uuid the UUID of the Insurance Plans
	 * @param companyId the primary key of the company
	 * @return the matching Insurance Plans, or an empty list if no matches were found
	 */
	@Override
	public List<InsurancePlan> getInsurancePlansByUuidAndCompanyId(
		String uuid, long companyId) {

		return insurancePlanPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of Insurance Plans matching the UUID and company.
	 *
	 * @param uuid the UUID of the Insurance Plans
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of Insurance Plans
	 * @param end the upper bound of the range of Insurance Plans (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching Insurance Plans, or an empty list if no matches were found
	 */
	@Override
	public List<InsurancePlan> getInsurancePlansByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<InsurancePlan> orderByComparator) {

		return insurancePlanPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the Insurance Plan matching the UUID and group.
	 *
	 * @param uuid the Insurance Plan's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Insurance Plan
	 * @throws PortalException if a matching Insurance Plan could not be found
	 */
	@Override
	public InsurancePlan getInsurancePlanByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return insurancePlanPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the Insurance Plans.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.InsurancePlanModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of Insurance Plans
	 * @param end the upper bound of the range of Insurance Plans (not inclusive)
	 * @return the range of Insurance Plans
	 */
	@Override
	public List<InsurancePlan> getInsurancePlans(int start, int end) {
		return insurancePlanPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of Insurance Plans.
	 *
	 * @return the number of Insurance Plans
	 */
	@Override
	public int getInsurancePlansCount() {
		return insurancePlanPersistence.countAll();
	}

	/**
	 * Updates the Insurance Plan in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect InsurancePlanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param insurancePlan the Insurance Plan
	 * @return the Insurance Plan that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public InsurancePlan updateInsurancePlan(InsurancePlan insurancePlan) {
		return insurancePlanPersistence.update(insurancePlan);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			InsurancePlanLocalService.class, IdentifiableOSGiService.class,
			CTService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		insurancePlanLocalService = (InsurancePlanLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return InsurancePlanLocalService.class.getName();
	}

	@Override
	public CTPersistence<InsurancePlan> getCTPersistence() {
		return insurancePlanPersistence;
	}

	@Override
	public Class<InsurancePlan> getModelClass() {
		return InsurancePlan.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<InsurancePlan>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(insurancePlanPersistence);
	}

	protected String getModelClassName() {
		return InsurancePlan.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = insurancePlanPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected BenefitUsagePersistence benefitUsagePersistence;

	protected InsurancePlanLocalService insurancePlanLocalService;

	@Reference
	protected InsurancePlanPersistence insurancePlanPersistence;

	@Reference
	protected PlanEnrollmentPersistence planEnrollmentPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		InsurancePlanLocalServiceBaseImpl.class);

}