/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.service.base;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.PlanEnrollment;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.PlanEnrollmentLocalService;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.BenefitUsagePersistence;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.InsurancePlanPersistence;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.persistence.PlanEnrollmentPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandler;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerRegistryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Criterion;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Disjunction;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Property;
import com.liferay.portal.kernel.dao.orm.PropertyFactoryUtil;
import com.liferay.portal.kernel.dao.orm.RestrictionsFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the Plan Enrollment local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.clarityvisionsolutions.insurance.benefits.tracker.service.impl.PlanEnrollmentLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.clarityvisionsolutions.insurance.benefits.tracker.service.impl.PlanEnrollmentLocalServiceImpl
 * @generated
 */
public abstract class PlanEnrollmentLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, PlanEnrollmentLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PlanEnrollmentLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.clarityvisionsolutions.insurance.benefits.tracker.service.PlanEnrollmentLocalServiceUtil</code>.
	 */

	/**
	 * Adds the Plan Enrollment to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PlanEnrollmentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param planEnrollment the Plan Enrollment
	 * @return the Plan Enrollment that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PlanEnrollment addPlanEnrollment(PlanEnrollment planEnrollment) {
		planEnrollment.setNew(true);

		return planEnrollmentPersistence.update(planEnrollment);
	}

	/**
	 * Creates a new Plan Enrollment with the primary key. Does not add the Plan Enrollment to the database.
	 *
	 * @param planEnrollmentId the primary key for the new Plan Enrollment
	 * @return the new Plan Enrollment
	 */
	@Override
	@Transactional(enabled = false)
	public PlanEnrollment createPlanEnrollment(long planEnrollmentId) {
		return planEnrollmentPersistence.create(planEnrollmentId);
	}

	/**
	 * Deletes the Plan Enrollment with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PlanEnrollmentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param planEnrollmentId the primary key of the Plan Enrollment
	 * @return the Plan Enrollment that was removed
	 * @throws PortalException if a Plan Enrollment with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PlanEnrollment deletePlanEnrollment(long planEnrollmentId)
		throws PortalException {

		return planEnrollmentPersistence.remove(planEnrollmentId);
	}

	/**
	 * Deletes the Plan Enrollment from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PlanEnrollmentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param planEnrollment the Plan Enrollment
	 * @return the Plan Enrollment that was removed
	 * @throws PortalException
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PlanEnrollment deletePlanEnrollment(PlanEnrollment planEnrollment)
		throws PortalException {

		return planEnrollmentPersistence.remove(planEnrollment);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return planEnrollmentPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PlanEnrollment.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return planEnrollmentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.PlanEnrollmentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return planEnrollmentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.PlanEnrollmentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return planEnrollmentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return planEnrollmentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return planEnrollmentPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PlanEnrollment fetchPlanEnrollment(long planEnrollmentId) {
		return planEnrollmentPersistence.fetchByPrimaryKey(planEnrollmentId);
	}

	/**
	 * Returns the Plan Enrollment matching the UUID and group.
	 *
	 * @param uuid the Plan Enrollment's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Plan Enrollment, or <code>null</code> if a matching Plan Enrollment could not be found
	 */
	@Override
	public PlanEnrollment fetchPlanEnrollmentByUuidAndGroupId(
		String uuid, long groupId) {

		return planEnrollmentPersistence.fetchByUUID_G(uuid, groupId);
	}

	@Override
	public PlanEnrollment fetchPlanEnrollmentByExternalReferenceCode(
		String externalReferenceCode, long groupId) {

		return planEnrollmentPersistence.fetchByERC_G(
			externalReferenceCode, groupId);
	}

	@Override
	public PlanEnrollment getPlanEnrollmentByExternalReferenceCode(
			String externalReferenceCode, long groupId)
		throws PortalException {

		return planEnrollmentPersistence.findByERC_G(
			externalReferenceCode, groupId);
	}

	/**
	 * Returns the Plan Enrollment with the primary key.
	 *
	 * @param planEnrollmentId the primary key of the Plan Enrollment
	 * @return the Plan Enrollment
	 * @throws PortalException if a Plan Enrollment with the primary key could not be found
	 */
	@Override
	public PlanEnrollment getPlanEnrollment(long planEnrollmentId)
		throws PortalException {

		return planEnrollmentPersistence.findByPrimaryKey(planEnrollmentId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(planEnrollmentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PlanEnrollment.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("planEnrollmentId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			planEnrollmentLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(PlanEnrollment.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"planEnrollmentId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(planEnrollmentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PlanEnrollment.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("planEnrollmentId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					Criterion modifiedDateCriterion =
						portletDataContext.getDateRangeCriteria("modifiedDate");

					Criterion statusDateCriterion =
						portletDataContext.getDateRangeCriteria("statusDate");

					if ((modifiedDateCriterion != null) &&
						(statusDateCriterion != null)) {

						Disjunction disjunction =
							RestrictionsFactoryUtil.disjunction();

						disjunction.add(modifiedDateCriterion);
						disjunction.add(statusDateCriterion);

						dynamicQuery.add(disjunction);
					}

					Property workflowStatusProperty =
						PropertyFactoryUtil.forName("status");

					if (portletDataContext.isInitialPublication()) {
						dynamicQuery.add(
							workflowStatusProperty.ne(
								WorkflowConstants.STATUS_IN_TRASH));
					}
					else {
						StagedModelDataHandler<?> stagedModelDataHandler =
							StagedModelDataHandlerRegistryUtil.
								getStagedModelDataHandler(
									PlanEnrollment.class.getName());

						dynamicQuery.add(
							workflowStatusProperty.in(
								stagedModelDataHandler.
									getExportableStatuses()));
					}
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<PlanEnrollment>() {

				@Override
				public void performAction(PlanEnrollment planEnrollment)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, planEnrollment);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(PlanEnrollment.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return planEnrollmentPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement PlanEnrollmentLocalServiceImpl#deletePlanEnrollment(PlanEnrollment) to avoid orphaned data");
		}

		return planEnrollmentLocalService.deletePlanEnrollment(
			(PlanEnrollment)persistedModel);
	}

	@Override
	public BasePersistence<PlanEnrollment> getBasePersistence() {
		return planEnrollmentPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return planEnrollmentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the Plan Enrollments matching the UUID and company.
	 *
	 * @param uuid the UUID of the Plan Enrollments
	 * @param companyId the primary key of the company
	 * @return the matching Plan Enrollments, or an empty list if no matches were found
	 */
	@Override
	public List<PlanEnrollment> getPlanEnrollmentsByUuidAndCompanyId(
		String uuid, long companyId) {

		return planEnrollmentPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of Plan Enrollments matching the UUID and company.
	 *
	 * @param uuid the UUID of the Plan Enrollments
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of Plan Enrollments
	 * @param end the upper bound of the range of Plan Enrollments (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching Plan Enrollments, or an empty list if no matches were found
	 */
	@Override
	public List<PlanEnrollment> getPlanEnrollmentsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<PlanEnrollment> orderByComparator) {

		return planEnrollmentPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the Plan Enrollment matching the UUID and group.
	 *
	 * @param uuid the Plan Enrollment's UUID
	 * @param groupId the primary key of the group
	 * @return the matching Plan Enrollment
	 * @throws PortalException if a matching Plan Enrollment could not be found
	 */
	@Override
	public PlanEnrollment getPlanEnrollmentByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return planEnrollmentPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the Plan Enrollments.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.clarityvisionsolutions.insurance.benefits.tracker.model.impl.PlanEnrollmentModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of Plan Enrollments
	 * @param end the upper bound of the range of Plan Enrollments (not inclusive)
	 * @return the range of Plan Enrollments
	 */
	@Override
	public List<PlanEnrollment> getPlanEnrollments(int start, int end) {
		return planEnrollmentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of Plan Enrollments.
	 *
	 * @return the number of Plan Enrollments
	 */
	@Override
	public int getPlanEnrollmentsCount() {
		return planEnrollmentPersistence.countAll();
	}

	/**
	 * Updates the Plan Enrollment in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PlanEnrollmentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param planEnrollment the Plan Enrollment
	 * @return the Plan Enrollment that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PlanEnrollment updatePlanEnrollment(PlanEnrollment planEnrollment) {
		return planEnrollmentPersistence.update(planEnrollment);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PlanEnrollmentLocalService.class, IdentifiableOSGiService.class,
			CTService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		planEnrollmentLocalService = (PlanEnrollmentLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PlanEnrollmentLocalService.class.getName();
	}

	@Override
	public CTPersistence<PlanEnrollment> getCTPersistence() {
		return planEnrollmentPersistence;
	}

	@Override
	public Class<PlanEnrollment> getModelClass() {
		return PlanEnrollment.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<PlanEnrollment>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(planEnrollmentPersistence);
	}

	protected String getModelClassName() {
		return PlanEnrollment.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = planEnrollmentPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected BenefitUsagePersistence benefitUsagePersistence;

	@Reference
	protected InsurancePlanPersistence insurancePlanPersistence;

	protected PlanEnrollmentLocalService planEnrollmentLocalService;

	@Reference
	protected PlanEnrollmentPersistence planEnrollmentPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		PlanEnrollmentLocalServiceBaseImpl.class);

}