/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.model.impl;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.BenefitUsage;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.BenefitUsageLocalServiceUtil;

/**
 * The extended model base implementation for the BenefitUsage service. Represents a row in the &quot;CIBT_BenefitUsage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BenefitUsageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BenefitUsageImpl
 * @see BenefitUsage
 * @generated
 */
public abstract class BenefitUsageBaseImpl
	extends BenefitUsageModelImpl implements BenefitUsage {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Benefit Usage model instance should use the <code>BenefitUsage</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BenefitUsageLocalServiceUtil.addBenefitUsage(this);
		}
		else {
			BenefitUsageLocalServiceUtil.updateBenefitUsage(this);
		}
	}

}