/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.model.impl;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.BenefitUsage;
import com.clarityvisionsolutions.insurance.benefits.tracker.model.BenefitUsageModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BenefitUsage service. Represents a row in the &quot;CIBT_BenefitUsage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BenefitUsageModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BenefitUsageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BenefitUsageImpl
 * @generated
 */
@JSON(strict = true)
public class BenefitUsageModelImpl
	extends BaseModelImpl<BenefitUsage> implements BenefitUsageModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Benefit Usage model instance should use the <code>BenefitUsage</code> interface instead.
	 */
	public static final String TABLE_NAME = "CIBT_BenefitUsage";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"benefitUsageId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"planEnrollmentId", Types.BIGINT},
		{"benefitType", Types.VARCHAR}, {"amountUsedCents", Types.BIGINT},
		{"serviceDate", Types.TIMESTAMP}, {"reference", Types.VARCHAR},
		{"notes", Types.VARCHAR}, {"sourceType", Types.VARCHAR},
		{"sourceReference", Types.VARCHAR}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("benefitUsageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("planEnrollmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("benefitType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("amountUsedCents", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("serviceDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("reference", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("notes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sourceType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sourceReference", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CIBT_BenefitUsage (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,benefitUsageId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,planEnrollmentId LONG,benefitType VARCHAR(75) null,amountUsedCents LONG,serviceDate DATE null,reference VARCHAR(75) null,notes STRING null,sourceType VARCHAR(75) null,sourceReference VARCHAR(75) null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,primary key (benefitUsageId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table CIBT_BenefitUsage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY benefitUsage.planEnrollmentId ASC, benefitUsage.serviceDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CIBT_BenefitUsage.planEnrollmentId ASC, CIBT_BenefitUsage.serviceDate DESC";

	public static final String ORDER_BY_SQL_INLINE_DISTINCT =
		" ORDER BY benefitUsage.planEnrollmentId ASC, benefitUsage.serviceDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLANENROLLMENTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SERVICEDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BenefitUsageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _benefitUsageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBenefitUsageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _benefitUsageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BenefitUsage.class;
	}

	@Override
	public String getModelClassName() {
		return BenefitUsage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BenefitUsage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BenefitUsage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BenefitUsage, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BenefitUsage)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BenefitUsage, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BenefitUsage, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BenefitUsage)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BenefitUsage, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BenefitUsage, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BenefitUsage, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BenefitUsage, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<BenefitUsage, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", BenefitUsage::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", BenefitUsage::getCtCollectionId);
			attributeGetterFunctions.put("uuid", BenefitUsage::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				BenefitUsage::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"benefitUsageId", BenefitUsage::getBenefitUsageId);
			attributeGetterFunctions.put("groupId", BenefitUsage::getGroupId);
			attributeGetterFunctions.put(
				"companyId", BenefitUsage::getCompanyId);
			attributeGetterFunctions.put("userId", BenefitUsage::getUserId);
			attributeGetterFunctions.put("userName", BenefitUsage::getUserName);
			attributeGetterFunctions.put(
				"createDate", BenefitUsage::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", BenefitUsage::getModifiedDate);
			attributeGetterFunctions.put(
				"planEnrollmentId", BenefitUsage::getPlanEnrollmentId);
			attributeGetterFunctions.put(
				"benefitType", BenefitUsage::getBenefitType);
			attributeGetterFunctions.put(
				"amountUsedCents", BenefitUsage::getAmountUsedCents);
			attributeGetterFunctions.put(
				"serviceDate", BenefitUsage::getServiceDate);
			attributeGetterFunctions.put(
				"reference", BenefitUsage::getReference);
			attributeGetterFunctions.put("notes", BenefitUsage::getNotes);
			attributeGetterFunctions.put(
				"sourceType", BenefitUsage::getSourceType);
			attributeGetterFunctions.put(
				"sourceReference", BenefitUsage::getSourceReference);
			attributeGetterFunctions.put("status", BenefitUsage::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", BenefitUsage::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", BenefitUsage::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", BenefitUsage::getStatusDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<BenefitUsage, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BenefitUsage, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<BenefitUsage, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<BenefitUsage, Long>)BenefitUsage::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<BenefitUsage, Long>)
					BenefitUsage::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<BenefitUsage, String>)BenefitUsage::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<BenefitUsage, String>)
					BenefitUsage::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"benefitUsageId",
				(BiConsumer<BenefitUsage, Long>)
					BenefitUsage::setBenefitUsageId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<BenefitUsage, Long>)BenefitUsage::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<BenefitUsage, Long>)BenefitUsage::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<BenefitUsage, Long>)BenefitUsage::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<BenefitUsage, String>)BenefitUsage::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<BenefitUsage, Date>)BenefitUsage::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<BenefitUsage, Date>)BenefitUsage::setModifiedDate);
			attributeSetterBiConsumers.put(
				"planEnrollmentId",
				(BiConsumer<BenefitUsage, Long>)
					BenefitUsage::setPlanEnrollmentId);
			attributeSetterBiConsumers.put(
				"benefitType",
				(BiConsumer<BenefitUsage, String>)BenefitUsage::setBenefitType);
			attributeSetterBiConsumers.put(
				"amountUsedCents",
				(BiConsumer<BenefitUsage, Long>)
					BenefitUsage::setAmountUsedCents);
			attributeSetterBiConsumers.put(
				"serviceDate",
				(BiConsumer<BenefitUsage, Date>)BenefitUsage::setServiceDate);
			attributeSetterBiConsumers.put(
				"reference",
				(BiConsumer<BenefitUsage, String>)BenefitUsage::setReference);
			attributeSetterBiConsumers.put(
				"notes",
				(BiConsumer<BenefitUsage, String>)BenefitUsage::setNotes);
			attributeSetterBiConsumers.put(
				"sourceType",
				(BiConsumer<BenefitUsage, String>)BenefitUsage::setSourceType);
			attributeSetterBiConsumers.put(
				"sourceReference",
				(BiConsumer<BenefitUsage, String>)
					BenefitUsage::setSourceReference);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<BenefitUsage, Integer>)BenefitUsage::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<BenefitUsage, Long>)
					BenefitUsage::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<BenefitUsage, String>)
					BenefitUsage::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<BenefitUsage, Date>)BenefitUsage::setStatusDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getBenefitUsageId() {
		return _benefitUsageId;
	}

	@Override
	public void setBenefitUsageId(long benefitUsageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitUsageId = benefitUsageId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPlanEnrollmentId() {
		return _planEnrollmentId;
	}

	@Override
	public void setPlanEnrollmentId(long planEnrollmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_planEnrollmentId = planEnrollmentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPlanEnrollmentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("planEnrollmentId"));
	}

	@JSON
	@Override
	public String getBenefitType() {
		if (_benefitType == null) {
			return "";
		}
		else {
			return _benefitType;
		}
	}

	@Override
	public void setBenefitType(String benefitType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitType = benefitType;
	}

	@JSON
	@Override
	public long getAmountUsedCents() {
		return _amountUsedCents;
	}

	@Override
	public void setAmountUsedCents(long amountUsedCents) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amountUsedCents = amountUsedCents;
	}

	@JSON
	@Override
	public Date getServiceDate() {
		return _serviceDate;
	}

	@Override
	public void setServiceDate(Date serviceDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_serviceDate = serviceDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalServiceDate() {
		return getColumnOriginalValue("serviceDate");
	}

	@JSON
	@Override
	public String getReference() {
		if (_reference == null) {
			return "";
		}
		else {
			return _reference;
		}
	}

	@Override
	public void setReference(String reference) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reference = reference;
	}

	@JSON
	@Override
	public String getNotes() {
		if (_notes == null) {
			return "";
		}
		else {
			return _notes;
		}
	}

	@Override
	public void setNotes(String notes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notes = notes;
	}

	@JSON
	@Override
	public String getSourceType() {
		if (_sourceType == null) {
			return "";
		}
		else {
			return _sourceType;
		}
	}

	@Override
	public void setSourceType(String sourceType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sourceType = sourceType;
	}

	@JSON
	@Override
	public String getSourceReference() {
		if (_sourceReference == null) {
			return "";
		}
		else {
			return _sourceReference;
		}
	}

	@Override
	public void setSourceReference(String sourceReference) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sourceReference = sourceReference;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(BenefitUsage.class.getName()));
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BenefitUsage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BenefitUsage toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BenefitUsage>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BenefitUsageImpl benefitUsageImpl = new BenefitUsageImpl();

		benefitUsageImpl.setMvccVersion(getMvccVersion());
		benefitUsageImpl.setCtCollectionId(getCtCollectionId());
		benefitUsageImpl.setUuid(getUuid());
		benefitUsageImpl.setExternalReferenceCode(getExternalReferenceCode());
		benefitUsageImpl.setBenefitUsageId(getBenefitUsageId());
		benefitUsageImpl.setGroupId(getGroupId());
		benefitUsageImpl.setCompanyId(getCompanyId());
		benefitUsageImpl.setUserId(getUserId());
		benefitUsageImpl.setUserName(getUserName());
		benefitUsageImpl.setCreateDate(getCreateDate());
		benefitUsageImpl.setModifiedDate(getModifiedDate());
		benefitUsageImpl.setPlanEnrollmentId(getPlanEnrollmentId());
		benefitUsageImpl.setBenefitType(getBenefitType());
		benefitUsageImpl.setAmountUsedCents(getAmountUsedCents());
		benefitUsageImpl.setServiceDate(getServiceDate());
		benefitUsageImpl.setReference(getReference());
		benefitUsageImpl.setNotes(getNotes());
		benefitUsageImpl.setSourceType(getSourceType());
		benefitUsageImpl.setSourceReference(getSourceReference());
		benefitUsageImpl.setStatus(getStatus());
		benefitUsageImpl.setStatusByUserId(getStatusByUserId());
		benefitUsageImpl.setStatusByUserName(getStatusByUserName());
		benefitUsageImpl.setStatusDate(getStatusDate());

		benefitUsageImpl.resetOriginalValues();

		return benefitUsageImpl;
	}

	@Override
	public BenefitUsage cloneWithOriginalValues() {
		BenefitUsageImpl benefitUsageImpl = new BenefitUsageImpl();

		benefitUsageImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		benefitUsageImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		benefitUsageImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		benefitUsageImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		benefitUsageImpl.setBenefitUsageId(
			this.<Long>getColumnOriginalValue("benefitUsageId"));
		benefitUsageImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		benefitUsageImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		benefitUsageImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		benefitUsageImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		benefitUsageImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		benefitUsageImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		benefitUsageImpl.setPlanEnrollmentId(
			this.<Long>getColumnOriginalValue("planEnrollmentId"));
		benefitUsageImpl.setBenefitType(
			this.<String>getColumnOriginalValue("benefitType"));
		benefitUsageImpl.setAmountUsedCents(
			this.<Long>getColumnOriginalValue("amountUsedCents"));
		benefitUsageImpl.setServiceDate(
			this.<Date>getColumnOriginalValue("serviceDate"));
		benefitUsageImpl.setReference(
			this.<String>getColumnOriginalValue("reference"));
		benefitUsageImpl.setNotes(this.<String>getColumnOriginalValue("notes"));
		benefitUsageImpl.setSourceType(
			this.<String>getColumnOriginalValue("sourceType"));
		benefitUsageImpl.setSourceReference(
			this.<String>getColumnOriginalValue("sourceReference"));
		benefitUsageImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		benefitUsageImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		benefitUsageImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		benefitUsageImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return benefitUsageImpl;
	}

	@Override
	public int compareTo(BenefitUsage benefitUsage) {
		int value = 0;

		if (getPlanEnrollmentId() < benefitUsage.getPlanEnrollmentId()) {
			value = -1;
		}
		else if (getPlanEnrollmentId() > benefitUsage.getPlanEnrollmentId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(
			getServiceDate(), benefitUsage.getServiceDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BenefitUsage)) {
			return false;
		}

		BenefitUsage benefitUsage = (BenefitUsage)object;

		long primaryKey = benefitUsage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BenefitUsage> toCacheModel() {
		BenefitUsageCacheModel benefitUsageCacheModel =
			new BenefitUsageCacheModel();

		benefitUsageCacheModel.mvccVersion = getMvccVersion();

		benefitUsageCacheModel.ctCollectionId = getCtCollectionId();

		benefitUsageCacheModel.uuid = getUuid();

		String uuid = benefitUsageCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			benefitUsageCacheModel.uuid = null;
		}

		benefitUsageCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			benefitUsageCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			benefitUsageCacheModel.externalReferenceCode = null;
		}

		benefitUsageCacheModel.benefitUsageId = getBenefitUsageId();

		benefitUsageCacheModel.groupId = getGroupId();

		benefitUsageCacheModel.companyId = getCompanyId();

		benefitUsageCacheModel.userId = getUserId();

		benefitUsageCacheModel.userName = getUserName();

		String userName = benefitUsageCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			benefitUsageCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			benefitUsageCacheModel.createDate = createDate.getTime();
		}
		else {
			benefitUsageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			benefitUsageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			benefitUsageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		benefitUsageCacheModel.planEnrollmentId = getPlanEnrollmentId();

		benefitUsageCacheModel.benefitType = getBenefitType();

		String benefitType = benefitUsageCacheModel.benefitType;

		if ((benefitType != null) && (benefitType.length() == 0)) {
			benefitUsageCacheModel.benefitType = null;
		}

		benefitUsageCacheModel.amountUsedCents = getAmountUsedCents();

		Date serviceDate = getServiceDate();

		if (serviceDate != null) {
			benefitUsageCacheModel.serviceDate = serviceDate.getTime();
		}
		else {
			benefitUsageCacheModel.serviceDate = Long.MIN_VALUE;
		}

		benefitUsageCacheModel.reference = getReference();

		String reference = benefitUsageCacheModel.reference;

		if ((reference != null) && (reference.length() == 0)) {
			benefitUsageCacheModel.reference = null;
		}

		benefitUsageCacheModel.notes = getNotes();

		String notes = benefitUsageCacheModel.notes;

		if ((notes != null) && (notes.length() == 0)) {
			benefitUsageCacheModel.notes = null;
		}

		benefitUsageCacheModel.sourceType = getSourceType();

		String sourceType = benefitUsageCacheModel.sourceType;

		if ((sourceType != null) && (sourceType.length() == 0)) {
			benefitUsageCacheModel.sourceType = null;
		}

		benefitUsageCacheModel.sourceReference = getSourceReference();

		String sourceReference = benefitUsageCacheModel.sourceReference;

		if ((sourceReference != null) && (sourceReference.length() == 0)) {
			benefitUsageCacheModel.sourceReference = null;
		}

		benefitUsageCacheModel.status = getStatus();

		benefitUsageCacheModel.statusByUserId = getStatusByUserId();

		benefitUsageCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = benefitUsageCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			benefitUsageCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			benefitUsageCacheModel.statusDate = statusDate.getTime();
		}
		else {
			benefitUsageCacheModel.statusDate = Long.MIN_VALUE;
		}

		return benefitUsageCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BenefitUsage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BenefitUsage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BenefitUsage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BenefitUsage)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BenefitUsage>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BenefitUsage.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private String _externalReferenceCode;
	private long _benefitUsageId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _planEnrollmentId;
	private String _benefitType;
	private long _amountUsedCents;
	private Date _serviceDate;
	private String _reference;
	private String _notes;
	private String _sourceType;
	private String _sourceReference;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BenefitUsage, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BenefitUsage)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("benefitUsageId", _benefitUsageId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("planEnrollmentId", _planEnrollmentId);
		_columnOriginalValues.put("benefitType", _benefitType);
		_columnOriginalValues.put("amountUsedCents", _amountUsedCents);
		_columnOriginalValues.put("serviceDate", _serviceDate);
		_columnOriginalValues.put("reference", _reference);
		_columnOriginalValues.put("notes", _notes);
		_columnOriginalValues.put("sourceType", _sourceType);
		_columnOriginalValues.put("sourceReference", _sourceReference);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("externalReferenceCode", 8L);

		columnBitmasks.put("benefitUsageId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		columnBitmasks.put("planEnrollmentId", 2048L);

		columnBitmasks.put("benefitType", 4096L);

		columnBitmasks.put("amountUsedCents", 8192L);

		columnBitmasks.put("serviceDate", 16384L);

		columnBitmasks.put("reference", 32768L);

		columnBitmasks.put("notes", 65536L);

		columnBitmasks.put("sourceType", 131072L);

		columnBitmasks.put("sourceReference", 262144L);

		columnBitmasks.put("status", 524288L);

		columnBitmasks.put("statusByUserId", 1048576L);

		columnBitmasks.put("statusByUserName", 2097152L);

		columnBitmasks.put("statusDate", 4194304L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BenefitUsage _escapedModel;

}