/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.model.impl;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.InsurancePlan;
import com.clarityvisionsolutions.insurance.benefits.tracker.model.InsurancePlanModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the InsurancePlan service. Represents a row in the &quot;CIBT_InsurancePlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>InsurancePlanModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InsurancePlanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InsurancePlanImpl
 * @generated
 */
@JSON(strict = true)
public class InsurancePlanModelImpl
	extends BaseModelImpl<InsurancePlan> implements InsurancePlanModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Insurance Plan model instance should use the <code>InsurancePlan</code> interface instead.
	 */
	public static final String TABLE_NAME = "CIBT_InsurancePlan";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"insurancePlanId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"planName", Types.VARCHAR},
		{"providerName", Types.VARCHAR}, {"active_", Types.BOOLEAN},
		{"annualExamAllowanceCents", Types.BIGINT},
		{"annualFramesAllowanceCents", Types.BIGINT},
		{"annualLensesAllowanceCents", Types.BIGINT},
		{"annualContactsAllowanceCents", Types.BIGINT},
		{"coveragePeriodMonths", Types.INTEGER}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("insurancePlanId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("planName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("providerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("annualExamAllowanceCents", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("annualFramesAllowanceCents", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("annualLensesAllowanceCents", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("annualContactsAllowanceCents", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("coveragePeriodMonths", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CIBT_InsurancePlan (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,insurancePlanId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,planName VARCHAR(75) null,providerName VARCHAR(75) null,active_ BOOLEAN,annualExamAllowanceCents LONG,annualFramesAllowanceCents LONG,annualLensesAllowanceCents LONG,annualContactsAllowanceCents LONG,coveragePeriodMonths INTEGER,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,primary key (insurancePlanId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table CIBT_InsurancePlan";

	public static final String ORDER_BY_JPQL =
		" ORDER BY insurancePlan.providerName ASC, insurancePlan.planName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CIBT_InsurancePlan.providerName ASC, CIBT_InsurancePlan.planName ASC";

	public static final String ORDER_BY_SQL_INLINE_DISTINCT =
		" ORDER BY insurancePlan.providerName ASC, insurancePlan.planName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROVIDERNAME_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLANNAME_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public InsurancePlanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _insurancePlanId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInsurancePlanId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _insurancePlanId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return InsurancePlan.class;
	}

	@Override
	public String getModelClassName() {
		return InsurancePlan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<InsurancePlan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<InsurancePlan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InsurancePlan, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((InsurancePlan)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<InsurancePlan, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<InsurancePlan, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(InsurancePlan)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<InsurancePlan, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<InsurancePlan, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<InsurancePlan, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<InsurancePlan, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<InsurancePlan, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", InsurancePlan::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", InsurancePlan::getCtCollectionId);
			attributeGetterFunctions.put("uuid", InsurancePlan::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				InsurancePlan::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"insurancePlanId", InsurancePlan::getInsurancePlanId);
			attributeGetterFunctions.put("groupId", InsurancePlan::getGroupId);
			attributeGetterFunctions.put(
				"companyId", InsurancePlan::getCompanyId);
			attributeGetterFunctions.put("userId", InsurancePlan::getUserId);
			attributeGetterFunctions.put(
				"userName", InsurancePlan::getUserName);
			attributeGetterFunctions.put(
				"createDate", InsurancePlan::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", InsurancePlan::getModifiedDate);
			attributeGetterFunctions.put(
				"planName", InsurancePlan::getPlanName);
			attributeGetterFunctions.put(
				"providerName", InsurancePlan::getProviderName);
			attributeGetterFunctions.put("active", InsurancePlan::getActive);
			attributeGetterFunctions.put(
				"annualExamAllowanceCents",
				InsurancePlan::getAnnualExamAllowanceCents);
			attributeGetterFunctions.put(
				"annualFramesAllowanceCents",
				InsurancePlan::getAnnualFramesAllowanceCents);
			attributeGetterFunctions.put(
				"annualLensesAllowanceCents",
				InsurancePlan::getAnnualLensesAllowanceCents);
			attributeGetterFunctions.put(
				"annualContactsAllowanceCents",
				InsurancePlan::getAnnualContactsAllowanceCents);
			attributeGetterFunctions.put(
				"coveragePeriodMonths", InsurancePlan::getCoveragePeriodMonths);
			attributeGetterFunctions.put("status", InsurancePlan::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", InsurancePlan::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", InsurancePlan::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", InsurancePlan::getStatusDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<InsurancePlan, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<InsurancePlan, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<InsurancePlan, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<InsurancePlan, Long>)InsurancePlan::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<InsurancePlan, Long>)
					InsurancePlan::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<InsurancePlan, String>)InsurancePlan::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<InsurancePlan, String>)
					InsurancePlan::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"insurancePlanId",
				(BiConsumer<InsurancePlan, Long>)
					InsurancePlan::setInsurancePlanId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<InsurancePlan, Long>)InsurancePlan::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<InsurancePlan, Long>)InsurancePlan::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<InsurancePlan, Long>)InsurancePlan::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<InsurancePlan, String>)InsurancePlan::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<InsurancePlan, Date>)InsurancePlan::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<InsurancePlan, Date>)
					InsurancePlan::setModifiedDate);
			attributeSetterBiConsumers.put(
				"planName",
				(BiConsumer<InsurancePlan, String>)InsurancePlan::setPlanName);
			attributeSetterBiConsumers.put(
				"providerName",
				(BiConsumer<InsurancePlan, String>)
					InsurancePlan::setProviderName);
			attributeSetterBiConsumers.put(
				"active",
				(BiConsumer<InsurancePlan, Boolean>)InsurancePlan::setActive);
			attributeSetterBiConsumers.put(
				"annualExamAllowanceCents",
				(BiConsumer<InsurancePlan, Long>)
					InsurancePlan::setAnnualExamAllowanceCents);
			attributeSetterBiConsumers.put(
				"annualFramesAllowanceCents",
				(BiConsumer<InsurancePlan, Long>)
					InsurancePlan::setAnnualFramesAllowanceCents);
			attributeSetterBiConsumers.put(
				"annualLensesAllowanceCents",
				(BiConsumer<InsurancePlan, Long>)
					InsurancePlan::setAnnualLensesAllowanceCents);
			attributeSetterBiConsumers.put(
				"annualContactsAllowanceCents",
				(BiConsumer<InsurancePlan, Long>)
					InsurancePlan::setAnnualContactsAllowanceCents);
			attributeSetterBiConsumers.put(
				"coveragePeriodMonths",
				(BiConsumer<InsurancePlan, Integer>)
					InsurancePlan::setCoveragePeriodMonths);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<InsurancePlan, Integer>)InsurancePlan::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<InsurancePlan, Long>)
					InsurancePlan::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<InsurancePlan, String>)
					InsurancePlan::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<InsurancePlan, Date>)InsurancePlan::setStatusDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getInsurancePlanId() {
		return _insurancePlanId;
	}

	@Override
	public void setInsurancePlanId(long insurancePlanId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insurancePlanId = insurancePlanId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getPlanName() {
		if (_planName == null) {
			return "";
		}
		else {
			return _planName;
		}
	}

	@Override
	public void setPlanName(String planName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_planName = planName;
	}

	@JSON
	@Override
	public String getProviderName() {
		if (_providerName == null) {
			return "";
		}
		else {
			return _providerName;
		}
	}

	@Override
	public void setProviderName(String providerName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_providerName = providerName;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalActive() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("active_"));
	}

	@JSON
	@Override
	public long getAnnualExamAllowanceCents() {
		return _annualExamAllowanceCents;
	}

	@Override
	public void setAnnualExamAllowanceCents(long annualExamAllowanceCents) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_annualExamAllowanceCents = annualExamAllowanceCents;
	}

	@JSON
	@Override
	public long getAnnualFramesAllowanceCents() {
		return _annualFramesAllowanceCents;
	}

	@Override
	public void setAnnualFramesAllowanceCents(long annualFramesAllowanceCents) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_annualFramesAllowanceCents = annualFramesAllowanceCents;
	}

	@JSON
	@Override
	public long getAnnualLensesAllowanceCents() {
		return _annualLensesAllowanceCents;
	}

	@Override
	public void setAnnualLensesAllowanceCents(long annualLensesAllowanceCents) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_annualLensesAllowanceCents = annualLensesAllowanceCents;
	}

	@JSON
	@Override
	public long getAnnualContactsAllowanceCents() {
		return _annualContactsAllowanceCents;
	}

	@Override
	public void setAnnualContactsAllowanceCents(
		long annualContactsAllowanceCents) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_annualContactsAllowanceCents = annualContactsAllowanceCents;
	}

	@JSON
	@Override
	public int getCoveragePeriodMonths() {
		return _coveragePeriodMonths;
	}

	@Override
	public void setCoveragePeriodMonths(int coveragePeriodMonths) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_coveragePeriodMonths = coveragePeriodMonths;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public long getContainerModelId() {
		return getInsurancePlanId();
	}

	@Override
	public void setContainerModelId(long containerModelId) {
		_insurancePlanId = containerModelId;
	}

	@Override
	public String getContainerModelName() {
		return String.valueOf(getContainerModelId());
	}

	@Override
	public long getParentContainerModelId() {
		return 0;
	}

	@Override
	public void setParentContainerModelId(long parentContainerModelId) {
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(InsurancePlan.class.getName()));
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), InsurancePlan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public InsurancePlan toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, InsurancePlan>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InsurancePlanImpl insurancePlanImpl = new InsurancePlanImpl();

		insurancePlanImpl.setMvccVersion(getMvccVersion());
		insurancePlanImpl.setCtCollectionId(getCtCollectionId());
		insurancePlanImpl.setUuid(getUuid());
		insurancePlanImpl.setExternalReferenceCode(getExternalReferenceCode());
		insurancePlanImpl.setInsurancePlanId(getInsurancePlanId());
		insurancePlanImpl.setGroupId(getGroupId());
		insurancePlanImpl.setCompanyId(getCompanyId());
		insurancePlanImpl.setUserId(getUserId());
		insurancePlanImpl.setUserName(getUserName());
		insurancePlanImpl.setCreateDate(getCreateDate());
		insurancePlanImpl.setModifiedDate(getModifiedDate());
		insurancePlanImpl.setPlanName(getPlanName());
		insurancePlanImpl.setProviderName(getProviderName());
		insurancePlanImpl.setActive(isActive());
		insurancePlanImpl.setAnnualExamAllowanceCents(
			getAnnualExamAllowanceCents());
		insurancePlanImpl.setAnnualFramesAllowanceCents(
			getAnnualFramesAllowanceCents());
		insurancePlanImpl.setAnnualLensesAllowanceCents(
			getAnnualLensesAllowanceCents());
		insurancePlanImpl.setAnnualContactsAllowanceCents(
			getAnnualContactsAllowanceCents());
		insurancePlanImpl.setCoveragePeriodMonths(getCoveragePeriodMonths());
		insurancePlanImpl.setStatus(getStatus());
		insurancePlanImpl.setStatusByUserId(getStatusByUserId());
		insurancePlanImpl.setStatusByUserName(getStatusByUserName());
		insurancePlanImpl.setStatusDate(getStatusDate());

		insurancePlanImpl.resetOriginalValues();

		return insurancePlanImpl;
	}

	@Override
	public InsurancePlan cloneWithOriginalValues() {
		InsurancePlanImpl insurancePlanImpl = new InsurancePlanImpl();

		insurancePlanImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		insurancePlanImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		insurancePlanImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		insurancePlanImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		insurancePlanImpl.setInsurancePlanId(
			this.<Long>getColumnOriginalValue("insurancePlanId"));
		insurancePlanImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		insurancePlanImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		insurancePlanImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		insurancePlanImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		insurancePlanImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		insurancePlanImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		insurancePlanImpl.setPlanName(
			this.<String>getColumnOriginalValue("planName"));
		insurancePlanImpl.setProviderName(
			this.<String>getColumnOriginalValue("providerName"));
		insurancePlanImpl.setActive(
			this.<Boolean>getColumnOriginalValue("active_"));
		insurancePlanImpl.setAnnualExamAllowanceCents(
			this.<Long>getColumnOriginalValue("annualExamAllowanceCents"));
		insurancePlanImpl.setAnnualFramesAllowanceCents(
			this.<Long>getColumnOriginalValue("annualFramesAllowanceCents"));
		insurancePlanImpl.setAnnualLensesAllowanceCents(
			this.<Long>getColumnOriginalValue("annualLensesAllowanceCents"));
		insurancePlanImpl.setAnnualContactsAllowanceCents(
			this.<Long>getColumnOriginalValue("annualContactsAllowanceCents"));
		insurancePlanImpl.setCoveragePeriodMonths(
			this.<Integer>getColumnOriginalValue("coveragePeriodMonths"));
		insurancePlanImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		insurancePlanImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		insurancePlanImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		insurancePlanImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return insurancePlanImpl;
	}

	@Override
	public int compareTo(InsurancePlan insurancePlan) {
		int value = 0;

		value = getProviderName().compareTo(insurancePlan.getProviderName());

		if (value != 0) {
			return value;
		}

		value = getPlanName().compareTo(insurancePlan.getPlanName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof InsurancePlan)) {
			return false;
		}

		InsurancePlan insurancePlan = (InsurancePlan)object;

		long primaryKey = insurancePlan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<InsurancePlan> toCacheModel() {
		InsurancePlanCacheModel insurancePlanCacheModel =
			new InsurancePlanCacheModel();

		insurancePlanCacheModel.mvccVersion = getMvccVersion();

		insurancePlanCacheModel.ctCollectionId = getCtCollectionId();

		insurancePlanCacheModel.uuid = getUuid();

		String uuid = insurancePlanCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			insurancePlanCacheModel.uuid = null;
		}

		insurancePlanCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			insurancePlanCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			insurancePlanCacheModel.externalReferenceCode = null;
		}

		insurancePlanCacheModel.insurancePlanId = getInsurancePlanId();

		insurancePlanCacheModel.groupId = getGroupId();

		insurancePlanCacheModel.companyId = getCompanyId();

		insurancePlanCacheModel.userId = getUserId();

		insurancePlanCacheModel.userName = getUserName();

		String userName = insurancePlanCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			insurancePlanCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			insurancePlanCacheModel.createDate = createDate.getTime();
		}
		else {
			insurancePlanCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			insurancePlanCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			insurancePlanCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		insurancePlanCacheModel.planName = getPlanName();

		String planName = insurancePlanCacheModel.planName;

		if ((planName != null) && (planName.length() == 0)) {
			insurancePlanCacheModel.planName = null;
		}

		insurancePlanCacheModel.providerName = getProviderName();

		String providerName = insurancePlanCacheModel.providerName;

		if ((providerName != null) && (providerName.length() == 0)) {
			insurancePlanCacheModel.providerName = null;
		}

		insurancePlanCacheModel.active = isActive();

		insurancePlanCacheModel.annualExamAllowanceCents =
			getAnnualExamAllowanceCents();

		insurancePlanCacheModel.annualFramesAllowanceCents =
			getAnnualFramesAllowanceCents();

		insurancePlanCacheModel.annualLensesAllowanceCents =
			getAnnualLensesAllowanceCents();

		insurancePlanCacheModel.annualContactsAllowanceCents =
			getAnnualContactsAllowanceCents();

		insurancePlanCacheModel.coveragePeriodMonths =
			getCoveragePeriodMonths();

		insurancePlanCacheModel.status = getStatus();

		insurancePlanCacheModel.statusByUserId = getStatusByUserId();

		insurancePlanCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = insurancePlanCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			insurancePlanCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			insurancePlanCacheModel.statusDate = statusDate.getTime();
		}
		else {
			insurancePlanCacheModel.statusDate = Long.MIN_VALUE;
		}

		return insurancePlanCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<InsurancePlan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<InsurancePlan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InsurancePlan, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((InsurancePlan)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, InsurancePlan>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					InsurancePlan.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private String _externalReferenceCode;
	private long _insurancePlanId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _planName;
	private String _providerName;
	private boolean _active;
	private long _annualExamAllowanceCents;
	private long _annualFramesAllowanceCents;
	private long _annualLensesAllowanceCents;
	private long _annualContactsAllowanceCents;
	private int _coveragePeriodMonths;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<InsurancePlan, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((InsurancePlan)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("insurancePlanId", _insurancePlanId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("planName", _planName);
		_columnOriginalValues.put("providerName", _providerName);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put(
			"annualExamAllowanceCents", _annualExamAllowanceCents);
		_columnOriginalValues.put(
			"annualFramesAllowanceCents", _annualFramesAllowanceCents);
		_columnOriginalValues.put(
			"annualLensesAllowanceCents", _annualLensesAllowanceCents);
		_columnOriginalValues.put(
			"annualContactsAllowanceCents", _annualContactsAllowanceCents);
		_columnOriginalValues.put(
			"coveragePeriodMonths", _coveragePeriodMonths);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("externalReferenceCode", 8L);

		columnBitmasks.put("insurancePlanId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		columnBitmasks.put("planName", 2048L);

		columnBitmasks.put("providerName", 4096L);

		columnBitmasks.put("active_", 8192L);

		columnBitmasks.put("annualExamAllowanceCents", 16384L);

		columnBitmasks.put("annualFramesAllowanceCents", 32768L);

		columnBitmasks.put("annualLensesAllowanceCents", 65536L);

		columnBitmasks.put("annualContactsAllowanceCents", 131072L);

		columnBitmasks.put("coveragePeriodMonths", 262144L);

		columnBitmasks.put("status", 524288L);

		columnBitmasks.put("statusByUserId", 1048576L);

		columnBitmasks.put("statusByUserName", 2097152L);

		columnBitmasks.put("statusDate", 4194304L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private InsurancePlan _escapedModel;

}