/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.model.impl;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.PlanEnrollment;
import com.clarityvisionsolutions.insurance.benefits.tracker.model.PlanEnrollmentModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PlanEnrollment service. Represents a row in the &quot;CIBT_PlanEnrollment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PlanEnrollmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanEnrollmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanEnrollmentImpl
 * @generated
 */
@JSON(strict = true)
public class PlanEnrollmentModelImpl
	extends BaseModelImpl<PlanEnrollment> implements PlanEnrollmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Plan Enrollment model instance should use the <code>PlanEnrollment</code> interface instead.
	 */
	public static final String TABLE_NAME = "CIBT_PlanEnrollment";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"planEnrollmentId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"insurancePlanId", Types.BIGINT},
		{"memberUserId", Types.BIGINT}, {"memberUserName", Types.VARCHAR},
		{"memberId", Types.VARCHAR}, {"groupNumber", Types.VARCHAR},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP},
		{"enrollmentStatus", Types.INTEGER}, {"notes", Types.VARCHAR},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("planEnrollmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("insurancePlanId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("memberUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("memberUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("memberId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("enrollmentStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("notes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CIBT_PlanEnrollment (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,planEnrollmentId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,insurancePlanId LONG,memberUserId LONG,memberUserName VARCHAR(75) null,memberId VARCHAR(75) null,groupNumber VARCHAR(75) null,startDate DATE null,endDate DATE null,enrollmentStatus INTEGER,notes STRING null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,primary key (planEnrollmentId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table CIBT_PlanEnrollment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY planEnrollment.insurancePlanId ASC, planEnrollment.memberUserId ASC, planEnrollment.startDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CIBT_PlanEnrollment.insurancePlanId ASC, CIBT_PlanEnrollment.memberUserId ASC, CIBT_PlanEnrollment.startDate DESC";

	public static final String ORDER_BY_SQL_INLINE_DISTINCT =
		" ORDER BY planEnrollment.insurancePlanId ASC, planEnrollment.memberUserId ASC, planEnrollment.startDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENROLLMENTSTATUS_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INSURANCEPLANID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MEMBERID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MEMBERUSERID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 512L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STARTDATE_COLUMN_BITMASK = 1024L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PlanEnrollmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _planEnrollmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPlanEnrollmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _planEnrollmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PlanEnrollment.class;
	}

	@Override
	public String getModelClassName() {
		return PlanEnrollment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PlanEnrollment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PlanEnrollment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PlanEnrollment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PlanEnrollment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PlanEnrollment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PlanEnrollment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PlanEnrollment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PlanEnrollment, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PlanEnrollment, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<PlanEnrollment, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<PlanEnrollment, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<PlanEnrollment, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", PlanEnrollment::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", PlanEnrollment::getCtCollectionId);
			attributeGetterFunctions.put("uuid", PlanEnrollment::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				PlanEnrollment::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"planEnrollmentId", PlanEnrollment::getPlanEnrollmentId);
			attributeGetterFunctions.put("groupId", PlanEnrollment::getGroupId);
			attributeGetterFunctions.put(
				"companyId", PlanEnrollment::getCompanyId);
			attributeGetterFunctions.put("userId", PlanEnrollment::getUserId);
			attributeGetterFunctions.put(
				"userName", PlanEnrollment::getUserName);
			attributeGetterFunctions.put(
				"createDate", PlanEnrollment::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", PlanEnrollment::getModifiedDate);
			attributeGetterFunctions.put(
				"insurancePlanId", PlanEnrollment::getInsurancePlanId);
			attributeGetterFunctions.put(
				"memberUserId", PlanEnrollment::getMemberUserId);
			attributeGetterFunctions.put(
				"memberUserName", PlanEnrollment::getMemberUserName);
			attributeGetterFunctions.put(
				"memberId", PlanEnrollment::getMemberId);
			attributeGetterFunctions.put(
				"groupNumber", PlanEnrollment::getGroupNumber);
			attributeGetterFunctions.put(
				"startDate", PlanEnrollment::getStartDate);
			attributeGetterFunctions.put("endDate", PlanEnrollment::getEndDate);
			attributeGetterFunctions.put(
				"enrollmentStatus", PlanEnrollment::getEnrollmentStatus);
			attributeGetterFunctions.put("notes", PlanEnrollment::getNotes);
			attributeGetterFunctions.put("status", PlanEnrollment::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", PlanEnrollment::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", PlanEnrollment::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", PlanEnrollment::getStatusDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<PlanEnrollment, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PlanEnrollment, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<PlanEnrollment, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<PlanEnrollment, Long>)
					PlanEnrollment::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<PlanEnrollment, Long>)
					PlanEnrollment::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<PlanEnrollment, String>)PlanEnrollment::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<PlanEnrollment, String>)
					PlanEnrollment::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"planEnrollmentId",
				(BiConsumer<PlanEnrollment, Long>)
					PlanEnrollment::setPlanEnrollmentId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<PlanEnrollment, Long>)PlanEnrollment::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PlanEnrollment, Long>)PlanEnrollment::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<PlanEnrollment, Long>)PlanEnrollment::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<PlanEnrollment, String>)
					PlanEnrollment::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<PlanEnrollment, Date>)
					PlanEnrollment::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<PlanEnrollment, Date>)
					PlanEnrollment::setModifiedDate);
			attributeSetterBiConsumers.put(
				"insurancePlanId",
				(BiConsumer<PlanEnrollment, Long>)
					PlanEnrollment::setInsurancePlanId);
			attributeSetterBiConsumers.put(
				"memberUserId",
				(BiConsumer<PlanEnrollment, Long>)
					PlanEnrollment::setMemberUserId);
			attributeSetterBiConsumers.put(
				"memberUserName",
				(BiConsumer<PlanEnrollment, String>)
					PlanEnrollment::setMemberUserName);
			attributeSetterBiConsumers.put(
				"memberId",
				(BiConsumer<PlanEnrollment, String>)
					PlanEnrollment::setMemberId);
			attributeSetterBiConsumers.put(
				"groupNumber",
				(BiConsumer<PlanEnrollment, String>)
					PlanEnrollment::setGroupNumber);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<PlanEnrollment, Date>)PlanEnrollment::setStartDate);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<PlanEnrollment, Date>)PlanEnrollment::setEndDate);
			attributeSetterBiConsumers.put(
				"enrollmentStatus",
				(BiConsumer<PlanEnrollment, Integer>)
					PlanEnrollment::setEnrollmentStatus);
			attributeSetterBiConsumers.put(
				"notes",
				(BiConsumer<PlanEnrollment, String>)PlanEnrollment::setNotes);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<PlanEnrollment, Integer>)PlanEnrollment::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<PlanEnrollment, Long>)
					PlanEnrollment::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<PlanEnrollment, String>)
					PlanEnrollment::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<PlanEnrollment, Date>)
					PlanEnrollment::setStatusDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getPlanEnrollmentId() {
		return _planEnrollmentId;
	}

	@Override
	public void setPlanEnrollmentId(long planEnrollmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_planEnrollmentId = planEnrollmentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getInsurancePlanId() {
		return _insurancePlanId;
	}

	@Override
	public void setInsurancePlanId(long insurancePlanId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insurancePlanId = insurancePlanId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalInsurancePlanId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("insurancePlanId"));
	}

	@JSON
	@Override
	public long getMemberUserId() {
		return _memberUserId;
	}

	@Override
	public void setMemberUserId(long memberUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_memberUserId = memberUserId;
	}

	@Override
	public String getMemberUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getMemberUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setMemberUserUuid(String memberUserUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalMemberUserId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("memberUserId"));
	}

	@JSON
	@Override
	public String getMemberUserName() {
		if (_memberUserName == null) {
			return "";
		}
		else {
			return _memberUserName;
		}
	}

	@Override
	public void setMemberUserName(String memberUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_memberUserName = memberUserName;
	}

	@JSON
	@Override
	public String getMemberId() {
		if (_memberId == null) {
			return "";
		}
		else {
			return _memberId;
		}
	}

	@Override
	public void setMemberId(String memberId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_memberId = memberId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalMemberId() {
		return getColumnOriginalValue("memberId");
	}

	@JSON
	@Override
	public String getGroupNumber() {
		if (_groupNumber == null) {
			return "";
		}
		else {
			return _groupNumber;
		}
	}

	@Override
	public void setGroupNumber(String groupNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupNumber = groupNumber;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@JSON
	@Override
	public int getEnrollmentStatus() {
		return _enrollmentStatus;
	}

	@Override
	public void setEnrollmentStatus(int enrollmentStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_enrollmentStatus = enrollmentStatus;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalEnrollmentStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("enrollmentStatus"));
	}

	@JSON
	@Override
	public String getNotes() {
		if (_notes == null) {
			return "";
		}
		else {
			return _notes;
		}
	}

	@Override
	public void setNotes(String notes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notes = notes;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public long getContainerModelId() {
		return getPlanEnrollmentId();
	}

	@Override
	public void setContainerModelId(long containerModelId) {
		_planEnrollmentId = containerModelId;
	}

	@Override
	public long getParentContainerModelId() {
		return getInsurancePlanId();
	}

	@Override
	public void setParentContainerModelId(long parentContainerModelId) {
		_insurancePlanId = parentContainerModelId;
	}

	@Override
	public String getContainerModelName() {
		return String.valueOf(getContainerModelId());
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(PlanEnrollment.class.getName()));
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PlanEnrollment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PlanEnrollment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PlanEnrollment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PlanEnrollmentImpl planEnrollmentImpl = new PlanEnrollmentImpl();

		planEnrollmentImpl.setMvccVersion(getMvccVersion());
		planEnrollmentImpl.setCtCollectionId(getCtCollectionId());
		planEnrollmentImpl.setUuid(getUuid());
		planEnrollmentImpl.setExternalReferenceCode(getExternalReferenceCode());
		planEnrollmentImpl.setPlanEnrollmentId(getPlanEnrollmentId());
		planEnrollmentImpl.setGroupId(getGroupId());
		planEnrollmentImpl.setCompanyId(getCompanyId());
		planEnrollmentImpl.setUserId(getUserId());
		planEnrollmentImpl.setUserName(getUserName());
		planEnrollmentImpl.setCreateDate(getCreateDate());
		planEnrollmentImpl.setModifiedDate(getModifiedDate());
		planEnrollmentImpl.setInsurancePlanId(getInsurancePlanId());
		planEnrollmentImpl.setMemberUserId(getMemberUserId());
		planEnrollmentImpl.setMemberUserName(getMemberUserName());
		planEnrollmentImpl.setMemberId(getMemberId());
		planEnrollmentImpl.setGroupNumber(getGroupNumber());
		planEnrollmentImpl.setStartDate(getStartDate());
		planEnrollmentImpl.setEndDate(getEndDate());
		planEnrollmentImpl.setEnrollmentStatus(getEnrollmentStatus());
		planEnrollmentImpl.setNotes(getNotes());
		planEnrollmentImpl.setStatus(getStatus());
		planEnrollmentImpl.setStatusByUserId(getStatusByUserId());
		planEnrollmentImpl.setStatusByUserName(getStatusByUserName());
		planEnrollmentImpl.setStatusDate(getStatusDate());

		planEnrollmentImpl.resetOriginalValues();

		return planEnrollmentImpl;
	}

	@Override
	public PlanEnrollment cloneWithOriginalValues() {
		PlanEnrollmentImpl planEnrollmentImpl = new PlanEnrollmentImpl();

		planEnrollmentImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		planEnrollmentImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		planEnrollmentImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		planEnrollmentImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		planEnrollmentImpl.setPlanEnrollmentId(
			this.<Long>getColumnOriginalValue("planEnrollmentId"));
		planEnrollmentImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		planEnrollmentImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		planEnrollmentImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		planEnrollmentImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		planEnrollmentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		planEnrollmentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		planEnrollmentImpl.setInsurancePlanId(
			this.<Long>getColumnOriginalValue("insurancePlanId"));
		planEnrollmentImpl.setMemberUserId(
			this.<Long>getColumnOriginalValue("memberUserId"));
		planEnrollmentImpl.setMemberUserName(
			this.<String>getColumnOriginalValue("memberUserName"));
		planEnrollmentImpl.setMemberId(
			this.<String>getColumnOriginalValue("memberId"));
		planEnrollmentImpl.setGroupNumber(
			this.<String>getColumnOriginalValue("groupNumber"));
		planEnrollmentImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		planEnrollmentImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));
		planEnrollmentImpl.setEnrollmentStatus(
			this.<Integer>getColumnOriginalValue("enrollmentStatus"));
		planEnrollmentImpl.setNotes(
			this.<String>getColumnOriginalValue("notes"));
		planEnrollmentImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		planEnrollmentImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		planEnrollmentImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		planEnrollmentImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return planEnrollmentImpl;
	}

	@Override
	public int compareTo(PlanEnrollment planEnrollment) {
		int value = 0;

		if (getInsurancePlanId() < planEnrollment.getInsurancePlanId()) {
			value = -1;
		}
		else if (getInsurancePlanId() > planEnrollment.getInsurancePlanId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getMemberUserId() < planEnrollment.getMemberUserId()) {
			value = -1;
		}
		else if (getMemberUserId() > planEnrollment.getMemberUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(
			getStartDate(), planEnrollment.getStartDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PlanEnrollment)) {
			return false;
		}

		PlanEnrollment planEnrollment = (PlanEnrollment)object;

		long primaryKey = planEnrollment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PlanEnrollment> toCacheModel() {
		PlanEnrollmentCacheModel planEnrollmentCacheModel =
			new PlanEnrollmentCacheModel();

		planEnrollmentCacheModel.mvccVersion = getMvccVersion();

		planEnrollmentCacheModel.ctCollectionId = getCtCollectionId();

		planEnrollmentCacheModel.uuid = getUuid();

		String uuid = planEnrollmentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			planEnrollmentCacheModel.uuid = null;
		}

		planEnrollmentCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			planEnrollmentCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			planEnrollmentCacheModel.externalReferenceCode = null;
		}

		planEnrollmentCacheModel.planEnrollmentId = getPlanEnrollmentId();

		planEnrollmentCacheModel.groupId = getGroupId();

		planEnrollmentCacheModel.companyId = getCompanyId();

		planEnrollmentCacheModel.userId = getUserId();

		planEnrollmentCacheModel.userName = getUserName();

		String userName = planEnrollmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			planEnrollmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			planEnrollmentCacheModel.createDate = createDate.getTime();
		}
		else {
			planEnrollmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			planEnrollmentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			planEnrollmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		planEnrollmentCacheModel.insurancePlanId = getInsurancePlanId();

		planEnrollmentCacheModel.memberUserId = getMemberUserId();

		planEnrollmentCacheModel.memberUserName = getMemberUserName();

		String memberUserName = planEnrollmentCacheModel.memberUserName;

		if ((memberUserName != null) && (memberUserName.length() == 0)) {
			planEnrollmentCacheModel.memberUserName = null;
		}

		planEnrollmentCacheModel.memberId = getMemberId();

		String memberId = planEnrollmentCacheModel.memberId;

		if ((memberId != null) && (memberId.length() == 0)) {
			planEnrollmentCacheModel.memberId = null;
		}

		planEnrollmentCacheModel.groupNumber = getGroupNumber();

		String groupNumber = planEnrollmentCacheModel.groupNumber;

		if ((groupNumber != null) && (groupNumber.length() == 0)) {
			planEnrollmentCacheModel.groupNumber = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			planEnrollmentCacheModel.startDate = startDate.getTime();
		}
		else {
			planEnrollmentCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			planEnrollmentCacheModel.endDate = endDate.getTime();
		}
		else {
			planEnrollmentCacheModel.endDate = Long.MIN_VALUE;
		}

		planEnrollmentCacheModel.enrollmentStatus = getEnrollmentStatus();

		planEnrollmentCacheModel.notes = getNotes();

		String notes = planEnrollmentCacheModel.notes;

		if ((notes != null) && (notes.length() == 0)) {
			planEnrollmentCacheModel.notes = null;
		}

		planEnrollmentCacheModel.status = getStatus();

		planEnrollmentCacheModel.statusByUserId = getStatusByUserId();

		planEnrollmentCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = planEnrollmentCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			planEnrollmentCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			planEnrollmentCacheModel.statusDate = statusDate.getTime();
		}
		else {
			planEnrollmentCacheModel.statusDate = Long.MIN_VALUE;
		}

		return planEnrollmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PlanEnrollment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PlanEnrollment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PlanEnrollment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PlanEnrollment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PlanEnrollment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PlanEnrollment.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private String _externalReferenceCode;
	private long _planEnrollmentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _insurancePlanId;
	private long _memberUserId;
	private String _memberUserName;
	private String _memberId;
	private String _groupNumber;
	private Date _startDate;
	private Date _endDate;
	private int _enrollmentStatus;
	private String _notes;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PlanEnrollment, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PlanEnrollment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("planEnrollmentId", _planEnrollmentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("insurancePlanId", _insurancePlanId);
		_columnOriginalValues.put("memberUserId", _memberUserId);
		_columnOriginalValues.put("memberUserName", _memberUserName);
		_columnOriginalValues.put("memberId", _memberId);
		_columnOriginalValues.put("groupNumber", _groupNumber);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("enrollmentStatus", _enrollmentStatus);
		_columnOriginalValues.put("notes", _notes);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("externalReferenceCode", 8L);

		columnBitmasks.put("planEnrollmentId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		columnBitmasks.put("insurancePlanId", 2048L);

		columnBitmasks.put("memberUserId", 4096L);

		columnBitmasks.put("memberUserName", 8192L);

		columnBitmasks.put("memberId", 16384L);

		columnBitmasks.put("groupNumber", 32768L);

		columnBitmasks.put("startDate", 65536L);

		columnBitmasks.put("endDate", 131072L);

		columnBitmasks.put("enrollmentStatus", 262144L);

		columnBitmasks.put("notes", 524288L);

		columnBitmasks.put("status", 1048576L);

		columnBitmasks.put("statusByUserId", 2097152L);

		columnBitmasks.put("statusByUserName", 4194304L);

		columnBitmasks.put("statusDate", 8388608L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PlanEnrollment _escapedModel;

}