/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.clarityvisionsolutions.insurance.benefits.tracker.model.impl;

import com.clarityvisionsolutions.insurance.benefits.tracker.model.PlanEnrollment;
import com.clarityvisionsolutions.insurance.benefits.tracker.service.PlanEnrollmentLocalServiceUtil;

/**
 * The extended model base implementation for the PlanEnrollment service. Represents a row in the &quot;CIBT_PlanEnrollment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanEnrollmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanEnrollmentImpl
 * @see PlanEnrollment
 * @generated
 */
public abstract class PlanEnrollmentBaseImpl
	extends PlanEnrollmentModelImpl implements PlanEnrollment {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Plan Enrollment model instance should use the <code>PlanEnrollment</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PlanEnrollmentLocalServiceUtil.addPlanEnrollment(this);
		}
		else {
			PlanEnrollmentLocalServiceUtil.updatePlanEnrollment(this);
		}
	}

}