create table CIBT_BenefitUsage (
	mvccVersion LONG default 0 not null,
	ctCollectionId LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	benefitUsageId LONG not null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	planEnrollmentId LONG,
	benefitType VARCHAR(75) null,
	amountUsedCents LONG,
	serviceDate DATE null,
	reference VARCHAR(75) null,
	notes STRING null,
	sourceType VARCHAR(75) null,
	sourceReference VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	primary key (benefitUsageId, ctCollectionId)
);

create table CIBT_InsurancePlan (
	mvccVersion LONG default 0 not null,
	ctCollectionId LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	insurancePlanId LONG not null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	planName VARCHAR(75) null,
	providerName VARCHAR(75) null,
	active_ BOOLEAN,
	annualExamAllowanceCents LONG,
	annualFramesAllowanceCents LONG,
	annualLensesAllowanceCents LONG,
	annualContactsAllowanceCents LONG,
	coveragePeriodMonths INTEGER,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	primary key (insurancePlanId, ctCollectionId)
);

create table CIBT_PlanEnrollment (
	mvccVersion LONG default 0 not null,
	ctCollectionId LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	planEnrollmentId LONG not null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	insurancePlanId LONG,
	memberUserId LONG,
	memberUserName VARCHAR(75) null,
	memberId VARCHAR(75) null,
	groupNumber VARCHAR(75) null,
	startDate DATE null,
	endDate DATE null,
	enrollmentStatus INTEGER,
	notes STRING null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	primary key (planEnrollmentId, ctCollectionId)
);